### ISSUE TITLE
项目导入eclipse产生的问题

### ISSUE THREAD

**Issue by weiliangdexinqing** [zzz40500/HeadsUp#1]
hello,HeadsUp类中继承的android.support.v4.app.NotificationCompat.Builder，有版本问题限制吗？我导入eclipse后，HeadsUp中的setSortKey等部分方法无法继承

**Comment by weiliangdexinqing** [comment]
还有这个类com.nineoldandroids.animation是引用的哪里的？

**Comment by zzz40500** [comment]
ȥ���� NineOldAndroids ��jar

�����ҵ� iPhone

> �� 2015��4��8�գ�16:03��weiliangdexinqing notifications@github.com д���
> 
> com.nineoldandroids.animation

**Comment by zzz40500** [comment]
com.nineoldandroids.animation  该类来自 NineOldAndroids  这个库
